[ip]
name = "olo-intf"
uuid = "e9gwu2h42eekqt8lz8ga7rnnb"
version = "2.1.0"
description = "Interfaces (e.g. I2C, synchronizer, SPI, ...)"
library = "olo"
source = "https://github.com/chaseruskin/open-logic/archive/{{orbit.ip.version}}.zip"

# See more keys and their definitions at https://chaseruskin.github.io/orbit/reference/manifest.html

[dependencies]
olo-base = "2.1.0"