[ip]
name = "olo-base"
uuid = "d00odbrxjv7u0utenigoplox6"
version = "2.1.0"
description = "Basic Circuitry (e.g. FIFOs, CDCs, ...)"
library = "olo"
source = "https://github.com/chaseruskin/open-logic/archive/{{orbit.ip.version}}.zip"

# See more keys and their definitions at https://chaseruskin.github.io/orbit/reference/manifest.html

[dependencies]
